# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, debug/* ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  demo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Test action
        uses: ./
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      
      - uses: actions/upload-artifact@v2
        if: always()
        with: 
          name: pngs
          path: images/

      - uses: actions/upload-artifact@v2
        with: 
          name: gif
          path: gol.gif
      
      - name: Commit results
        run: |
          git config user.email "you@example.com"
          git config user.name "Your Name"
          git commit gol.gif -m 'Re-build gol.gif' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
